### PR TITLE
build error std::runtime_error

### PR DESCRIPTION
**Pull request by Criispin**

### CODE REVIEW

**Review by vtnerd — COMMENTED** [review]
Where is this failing? These headers don't appear to need it directly.

**Comment by vtnerd** [comment]
I've looked at this a few times, but I don't see where `<stdexcept>` is needed for these headers. Are there some cpp files that need this header directly?

**Comment by Criispin** [comment]
my compiler throws this at me

`../src/display/falling_text.cpp:86:18: Fehler: »runtime_error« ist kein Element von »std«
   86 |       throw std::runtime_error{"failed to create ncurses window"};
`

https://github.com/vtnerd/motrix/blob/163ec8f04c15d6024d54c79f6d6c5b336ecb0446/src/display/falling_text.cpp#L86

**Comment by nalal** [comment]
I can confirm this issue, it seems that the function `std::runtime_error` (seen in `src/display/falling_text.cpp:86` and `src/display/system_warning.cpp:48`) requires the library `<stdexcept>`.
Building on Arch, gcc version 10.2.0.
Acutally, I think I see what's happened, it seems that the include in `src/display/window.cpp` was supposed to be included in `src/display/window.hpp` which is what's inlcuded in the files where this seems to be an issue, moving that include to the header as opposed to the cpp file should resolve this as well.

**Comment by vtnerd** [comment]
The `#include <stdexcept>` should be in those two cpp fies, which call `throw std::runtime_error{...}`, as opposed to indirectly pulled from headers.

**Comment by jeffro256** [comment]
Wondering if this will be revisited and the `#includes` are added to the .cpp files since it fails to compile with g++ 12.3.0

**Comment by vtnerd** [comment]
@jeffro256 I have pushed the necessary includes to get it working with gcc 12+. I have also reverted back to the original system warning message. I am closing this, as its no longer needed.

**Comment by Ericmagsllonstrigs** [comment]
Very

**Comment by Ericmagsllonstrigs** [comment]
M

**Comment by Ericmagsllonstrigs** [comment]
- Nocturno

**Comment by Ericmagsllonstrigs** [comment]
I r

**Comment by Ericmagsllonstrigs** [comment]
Xxx

**Pull request closed without merging**
